// fTable localization file for 'fr' language.
// Converted automatically from legacy jQuery format
// fTable localization file for 'French' language.
//     Author: Guillaume Vernet
FTable.setMessages({
    serverCommunicationError: 'Erreur de communication avec le serveur.',
    loadingMessage: 'Chargement des données...',
    noDataAvailable: 'Aucune donnée !',
    addNewRecord: 'Ajouter',
    editRecord: 'Editer',
    areYouSure: 'Etes-vous sûr ?',
    deleteConfirmation: 'Cet enregistrement sera supprimé. Continuer ?',
    save: 'Sauvegarder',
    saving: 'Sauvegarde en cours...',
    cancel: 'Annuler',
    deleteText: 'Supprimer',
    deleting: 'Supression en cours...',
    error: 'Erreur',
    close: 'Fermer',
    confirm: 'Confirmer',
    cannotLoadOptionsFor: 'Impossible de charger les données du champ {0}',
    pagingInfo: 'Afficher {0} à {1} de {2}',
    canNotDeletedRecords: 'Impossible de supprimer {0} sur {1} enregistrement(s)!',
    deleteProgress: 'Supression {0} sur {1} enregistrement(s), en cours d\'exécution...',
    pageSizeChangeLabel: 'Nombre d\'enregistrement',
    gotoPageLabel: 'Aller à la page',
    sortingInfoPrefix: 'Tri appliqué : ',
    ascending: 'Ascendant',
    descending: 'Descendant',
    sortingInfoNone: 'Aucun tri appliqué',
    csvExport: 'CSV',
    printTable: '🖨️  Print',
    cloneRecord: 'Clone Record',
    resetSorting: 'Réinitialiser le tri',
    resetTable: "Réinitialiser le tableau",
    resetTableConfirm: 'Cela réinitialisera la visibilité des colonnes, la largeur des colonnes et la taille de la page à leurs valeurs par défaut. Voulez-vous continuer ?',
    resetTableTooltip: "Réinitialise la visibilité des colonnes, la largeur des colonnes et la taille de la page aux valeurs par défaut. Le tri n'est pas affecté.",
    resetSearch: 'Réinitialiser',
    columnSelectButton: "⊞ Colonnes'
});
